### ISSUE TITLE
Storybook example doesn't work

### ISSUE THREAD

**Issue by khmelevskii** [shadow-cljs/examples#29]
Hi,

I'm trying to run storybook example, but I have the following problem
```
COMPILED is not defined
ReferenceError: COMPILED is not defined
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:41823:1)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:42755:30)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:116133:1)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:116166:30)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at webpackContext (http://localhost:6006/static/preview.bundle.js:116112:9)
    at http://localhost:6006/static/preview.bundle.js:113185:36
```
can you please help me to fix it?

**Comment by thheller** [comment]
Sorry, I can't.

Storybook has changed completely over the last 2 years. I can't even get the old version to run anymore since installing the dependencies fails with

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

Guess it doesn't like my node version.

**Comment by khmelevskii** [comment]
@thheller yes, as I can see it related with storybook version. Btw if I remove all `^` in package.json I'm able to run storybook
```
  "dependencies": {
    "react": "16.2.0",
    "react-dom": "16.2.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "3.3.10",
    "@storybook/addon-links": "3.3.10",
    "@storybook/addons": "3.3.10",
    "@storybook/react": "3.3.10",
    "babel-core": "6.26.0",
    "shadow-cljs": "2.2.31"
  }
```

My node version is v10.16.0

**Comment by alex-dixon** [comment]
In JS projects I’ve had the best luck reinstalling storybook completely using the instructions on their site

**Comment by khmelevskii** [comment]
@thheller btw, when I try to use old storybook version but new shadow-cljs I have the same problem. So, I'm not sure that's storybook version issue

**Comment by khmelevskii** [comment]
@thheller I checked another shadow-cljs versions and I can see the storybook 3.3.10 works correctly with shadow-cljs v2.8.68 but not works with v2.8.69 and above

**Comment by thheller** [comment]
Hmm .69 upgraded to a new Closure Library release. I'm guessing something with the global `COMPILED` changed. I'll see if I can figure out which ns that is.

**Comment by thheller** [comment]
Do you happen to use `goog/promise/thenable.js` directly or via some dependency? That seems to have direct references to `COMPILED` besides `goog/base.js`.

```

goog/promise/thenable.js
101:  if (COMPILED) {
120:    if (COMPILED) {
```

**Comment by khmelevskii** [comment]
No, I've just completely copy your example https://github.com/shadow-cljs/examples/tree/master/cljs-storybook

**Comment by thheller** [comment]
@khmelevskii try `2.8.73` that should fix the `COMPILED` issue.

**Comment by khmelevskii** [comment]
@thheller I have another problem
```
Error
    at Function.goog.html.SafeHtml.getAttrNameAndValue_ (http://localhost:6006/static/preview.bundle.js:53642:15)
    at Function.goog.html.SafeHtml.stringifyAttributes (http://localhost:6006/static/preview.bundle.js:53824:42)
    at Function.goog.html.SafeHtml.createSafeHtmlTagSecurityPrivateDoNotAccessOrElse (http://localhost:6006/static/preview.bundle.js:53779:32)
    at Function.goog.html.SafeHtml.create (http://localhost:6006/static/preview.bundle.js:53496:29)
    at http://localhost:6006/static/preview.bundle.js:133468:53
    at Object.isSupported (http://localhost:6006/static/preview.bundle.js:57347:14)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:129289:99)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:128685:1)
```

**Comment by thheller** [comment]
Probably best to stick with an older version for now. I'll try to look into why `:npm-module` fails.

**Comment by thheller** [comment]
Try `2.8.74` when you get a chance. Found one issue that may have cause problems. At the very least it should make the error above more descriptive.

**Comment by khmelevskii** [comment]
@thheller unfortunately i have another problem 
```
Cannot find module 'undefined'.
Error: Cannot find module 'undefined'.
    at webpackContextResolve (http://localhost:6006/static/preview.bundle.js:68564:9)
    at webpackContext (http://localhost:6006/static/preview.bundle.js:68559:29)
    at ConfigApi._renderMain (http://localhost:6006/static/preview.bundle.js:66606:20)
    at render (http://localhost:6006/static/preview.bundle.js:66564:17)
    at ConfigApi.configure (http://localhost:6006/static/preview.bundle.js:66589:9)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:65635:68)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:65637:30)
    at __webpack_require__ (http://localhost:6006/static/preview.bundle.js:679:30)
    at fn (http://localhost:6006/static/preview.bundle.js:89:20)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:64302:18)
```
Can you reproduce this problem? Maybe it makes sense to create test repo with this problem for you?

**Comment by khmelevskii** [comment]
hey @thheller , just curious, are you going to deal with it in the nearest time?

**Comment by thheller** [comment]
Demo repo would help. Don't know which state you are in.

**Comment by thheller** [comment]
I tried setting up a newer storybook5 example but as soon as I put some CLJS sources into the stories folder it blows up. Guess I won't get this running. Not interested in trying further.

```
npm run storybook

> sb@1.0.0 storybook C:\Users\thheller\code\examples\cljs-storybook5\sb
> start-storybook -p 6006

info @storybook/react v5.2.6
info
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Using default Webpack setup.
info => Using base config because react-scripts is not installed.
13% building 29/36 modules 7 active C:\Users\thheller\code\examples\cljs-storybook5\sb\node_modules\@storybook\core\node_modules\core-js\es\symbol\index.js
<--- Last few GCs --->

[28284:00000245E281B7B0]    26141 ms: Scavenge 2041.8 (2050.4) -> 2041.1 (2050.4) MB, 4.1 / 0.0 ms  (average mu = 0.086, current mu = 0.042) allocation failure
[28284:00000245E281B7B0]    26146 ms: Scavenge 2041.9 (2050.4) -> 2041.4 (2050.4) MB, 4.8 / 0.0 ms  (average mu = 0.086, current mu = 0.042) allocation failure
[28284:00000245E281B7B0]    26152 ms: Scavenge 2042.0 (2050.4) -> 2042.0 (2050.9) MB, 5.4 / 0.0 ms  (average mu = 0.086, current mu = 0.042) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF6CE37982D]
    1: StubFrame [pc: 00007FF6CE2EF15D]
Security context: 0x03ee593c0911 <JSObject>
    2: SourceMapConsumer_allGeneratedPositionsFor [00000268349FB781] [C:\Users\thheller\code\examples\cljs-storybook5\sb\node_modules\source-map\lib\source-map-consumer.js:~178] [pc=000000853DFE1FE8](this=0x038ce91c0331 <BasicSourceMapConsumer map = 00000273FB6C3249>,0x0236b76b27b1 <Object map = 00000273FB6C2C59>)
  ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory```
